## Import Data Library

In [1]:
import time
import pandas as pd

##scrapping
from selenium import webdriver
from bs4 import BeautifulSoup

## Scraping Data

In [2]:
#List Kosong
nama_produk_clean = []
harga_clean = []
pengiriman_clean = []
diskon_clean = []

# Setup driver 
driver = webdriver.Chrome()
url = 'https://www.astronauts.id/search?q=minuman&source=homepage'
driver.get(url)

#agar tidak scroll terus (limiter)
scroll_limit = 5
count = 0

# Ambil ketinggian halaman saat ini (sebelum scroll)
last_height = driver.execute_script("return document.body.scrollHeight")

while True:

    #Memperlambat Scroll

    for i in range(0, last_height, 500):
        driver.execute_script(f"window.scrollTo(0, {i});")
        time.sleep(0.1)

    #Perintah JavaScript untuk scroll sampai ke paling bawah
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

    # menyesuaikan waktu sleep tergantung kecepatan internet/loading halaman
    time.sleep(5) 

    # Hitung ketinggian halaman baru setelah scroll dan loading
    new_height = driver.execute_script("return document.body.scrollHeight")
    
    count += 1
    print(f"Scroll ke-{count} selesai.")

    #rem
    if count >= scroll_limit:
        print(f"Sudah mencapai batas {scroll_limit} kali scroll. Berhenti paksa.")
        break

    # Cek ketinggian
    if new_height == last_height:
        print("Halaman sudah mencapai akhir.")
        break
    
    # Update last_height untuk berikutnya
    last_height = new_height

print("Sedang mengambil data HTML...")

html = driver.page_source

soup = BeautifulSoup(html, 'html.parser')

boxes = soup.find_all('div',{'class':'MuiBox-root css-1rgpaxo'})

for box in boxes:

    try:
        nama_produk = box.find('span',{'class':'MuiTypography-root MuiTypography-paragraph-tiny css-dndy4p'}) 
        nama_produk_clean.append(nama_produk.get_text())
    except:
        nama_produk_clean.append(None)

    try:
        harga = box.find('span',{'class':'MuiTypography-root MuiTypography-body-smallStrong css-tg7xtj'}) 
        harga_clean.append(harga.get_text())
    except:
        harga_clean.append(None)
    
    try:
        pengiriman = box.find('span',{'class':'MuiTypography-root MuiTypography-caption-tinyBold css-1jvjn92'}) 
        pengiriman_clean.append(pengiriman.get_text())
    except:
        pengiriman_clean.append(None)

    try:
        diskon = box.find('span',{'class':'MuiTypography-root MuiTypography-caption-tinyBold css-148eilu'}) 
        diskon_clean.append(diskon.get_text())
    except:
        diskon_clean.append(None)

Scroll ke-1 selesai.
Scroll ke-2 selesai.
Scroll ke-3 selesai.
Scroll ke-4 selesai.
Scroll ke-5 selesai.
Sudah mencapai batas 5 kali scroll. Berhenti paksa.
Sedang mengambil data HTML...

In [3]:
df_data = pd.DataFrame()

In [4]:
df_data['Nama Produk']=nama_produk_clean
df_data['harga'] = harga_clean
df_data['pengiriman'] = pengiriman_clean
df_data['diskon'] = diskon_clean


df_data.head(5)

                            Nama Produk    harga pengiriman diskon
0               S-tee Minuman Teh Kotak  Rp2.500    Instant   None
1  Yeo's Minuman Rasa Bunga Krisantemum  Rp7.700    Instant   None
2        Fanta Grape Minuman Soda Botol  Rp5.900    Instant   None
3       Coca-Cola Zero Minuman Soda Can  Rp6.400    Instant   None
4      A&W Sarsaparila Minuman Soda Can  Rp7.200    Instant   None

In [5]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Nama Produk  560 non-null    object
 1   harga        560 non-null    object
 2   pengiriman   560 non-null    object
 3   diskon       163 non-null    object
dtypes: object(4)
memory usage: 17.6+ KB

In [6]:
df_data.to_csv('milestone_scraping_astro_fix.csv')

In [7]:
driver.quit()

## Membersihkan Data

In [9]:
df_astro = pd.read_csv('milestone_scraping_astro_fix.csv')
df_astro.head(5)

   Unnamed: 0                           Nama Produk    harga pengiriman diskon
0           0               S-tee Minuman Teh Kotak  Rp2.500    Instant    NaN
1           1  Yeo's Minuman Rasa Bunga Krisantemum  Rp7.700    Instant    NaN
2           2        Fanta Grape Minuman Soda Botol  Rp5.900    Instant    NaN
3           3       Coca-Cola Zero Minuman Soda Can  Rp6.400    Instant    NaN
4           4      A&W Sarsaparila Minuman Soda Can  Rp7.200    Instant    NaN

In [10]:
df_astro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   560 non-null    int64
 1   Nama Produk  560 non-null    object
 2   harga        560 non-null    object
 3   pengiriman   560 non-null    object
 4   diskon       163 non-null    object
dtypes: int64(1), object(4)
memory usage: 22.0+ KB

In [12]:
df_astro.describe()

       Unnamed: 0
count  560.000000
mean   279.500000
std    161.802349
min      0.000000
25%    139.750000
50%    279.500000
75%    419.250000
max    559.000000

### Mengdrop column Unnamed: 0

In [13]:
df_astro = df_astro.drop(columns=['Unnamed: 0'])
df_astro

                              Nama Produk    harga pengiriman diskon
0                 S-tee Minuman Teh Kotak  Rp2.500    Instant    NaN
1    Yeo's Minuman Rasa Bunga Krisantemum  Rp7.700    Instant    NaN
2          Fanta Grape Minuman Soda Botol  Rp5.900    Instant    NaN
3         Coca-Cola Zero Minuman Soda Can  Rp6.400    Instant    NaN
4        A&W Sarsaparila Minuman Soda Can  Rp7.200    Instant    NaN
..                                    ...      ...        ...    ...
555           Cimory Marie Regal Susu UHT  Rp7.300    Instant    NaN
556        Cimory Choco Hazelnut Susu UHT  Rp6.000    Instant    18%
557          Cimory Choco Almond Susu UHT  Rp6.000    Instant    18%
558         Cimory Bebas Laktosa Susu UHT  Rp6.000    Instant    18%
559             Cimory Chocolate Susu UHT  Rp6.000    Instant    18%

[560 rows x 4 columns]

### Membersihkan dan mengubah tipe data kolom harga dan diskon

In [ ]:
# 1. Membersihkan kolom 'harga'
# Hapus 'Rp'-> hapus titik (.)-> ubah ke integer
df_astro['harga'] = df_astro['harga'].str.replace('Rp', '').str.replace('.', '').astype(int)

# 2. Membersihkan kolom 'diskon'
# Isi yang kosong dengan '0%' -> hapus tanda '%' -> ubah ke float
df_astro['diskon'] = df_astro['diskon'].fillna('0%').str.replace('%', '').astype(float)

df_astro.head(5)

### Cek Tipe Data

In [18]:
df_astro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Nama Produk  560 non-null    object
 1   harga        560 non-null    int32
 2   pengiriman   560 non-null    object
 3   diskon       560 non-null    float64
dtypes: float64(1), int32(1), object(2)
memory usage: 15.4+ KB

### Import Data to CSV

In [22]:
### index = false agar mudah di load di postgre

df_astro.to_csv('milestone_scraping_astro_bersih.csv',index=False)

### Dibawah hanya catatan html

'''html

gambar
<img alt="Kiranti Juice Orange" fetchpriority="high" decoding="async" data-nimg="fill" class="image" src="https://www.astronauts.id/mobile-web-assets/img/placeholder-product.svg" style="position: absolute; width: 100%; inset: 0px; object-fit: contain; color: transparent; max-width: 100%; display: block; opacity: 0; z-index: -1;">

quantity 
<span class="MuiTypography-root MuiTypography-caption-tiny css-1nnfyv8">150ml</span>

pengiriman
<span class="MuiTypography-root MuiTypography-caption-tinyBold css-1jvjn92">Instant</span>

nama
<span class="MuiTypography-root MuiTypography-paragraph-tiny css-dndy4p">Kiranti Juice Orange</span>

diskon
<span class="MuiTypography-root MuiTypography-caption-tinyBold css-148eilu">6%</span>

harga
<span class="MuiTypography-root MuiTypography-body-smallStrong css-tg7xtj">Rp9.500</span>

div

<div class="MuiBox-root css-1rgpaxo"><div class="MuiBox-root css-79elbk"><div class="MuiBox-root css-1vgrt3t" style="cursor: pointer; border: 1px solid rgb(36, 110, 229);"><div class="MuiBox-root css-b7jmoi"><div class="MuiBox-root css-bmzel2"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 3C10.8954 3 10 3.89543 10 5V10H5C3.89543 10 3 10.8954 3 12C3 13.1046 3.89543 14 5 14H10V19C10 20.1046 10.8954 21 12 21C13.1046 21 14 20.1046 14 19V14H19C20.1046 14 21 13.1046 21 12C21 10.8954 20.1046 10 19 10H14V5C14 3.89543 13.1046 3 12 3Z" fill="#246EE5"></path></svg></div></div></div><a href="/p/kiranti-juice-orange-150ml?locationId=591&amp;cartType=INSTANT"><div class="MuiBox-root css-1ljiyra"><div class="MuiBox-root css-13o7eu2"><div class="MuiBox-root css-79elbk"><img alt="Kiranti Juice Orange" fetchpriority="high" decoding="async" data-nimg="fill" class="image" src="https://www.astronauts.id/mobile-web-assets/img/placeholder-product.svg" style="position: absolute; width: 100%; inset: 0px; object-fit: contain; color: transparent; max-width: 100%; display: block; opacity: 0; z-index: -1;"></div></div><div class="MuiBox-root css-13o7eu2"><div class="MuiBox-root css-79elbk"><img alt="Kiranti Juice Orange" loading="lazy" decoding="async" data-nimg="fill" class="image" src="https://image.astronauts.cloud/product-images/2024/4/KirantiJuice150ml_35ba3348-f788-4af2-8470-9a4bd185bae9_700x700.png" style="position: absolute; width: 100%; inset: 0px; object-fit: contain; color: transparent; max-width: unset; display: block; opacity: 1; z-index: -1;"></div></div></div></a></div><div class="MuiBox-root css-xuz7fx"><a href="/p/kiranti-juice-orange-150ml?locationId=591&amp;cartType=INSTANT"><div class="MuiBox-root css-ks6u10"><span class="MuiTypography-root MuiTypography-body-smallStrong css-tg7xtj">Rp9.500</span><span class="MuiTypography-root MuiTypography-paragraph-tiny css-dndy4p">Kiranti Juice Orange</span><span class="MuiTypography-root MuiTypography-caption-tiny css-1nnfyv8">150ml</span></div><div class="MuiBox-root css-nl0e03"><div class="MuiBox-root css-13o7eu2"><div class="MuiBox-root css-0"><img alt="Delivery Type Icon" loading="lazy" width="12" height="12" decoding="async" data-nimg="1" class="image" src="https://storage.googleapis.com/astro-file/discovery/super-1p/Icon_Instant.png" style="color: transparent; max-width: 100%; object-fit: contain; display: block; height: 12px;"></div></div><span class="MuiTypography-root MuiTypography-caption-tinyBold css-1jvjn92">Instant</span></div></a></div></div>

'''